name: HelloWorld
description: ''
version: '1'
author: ''
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: helloworld
  parentArtefactID: kiranadminprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-06-27 06:58:26'
pipelines:
  pipelines/join_agg_sort:
    name: join_agg_sort
    description: Show an example of joining two datasets (customers and orders), aggregating
      (sales by customer), sorting (by totals)
    author: kiran+test+uimixp+2@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-09-19 13:02:56'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/customers_orders:
    name: customers_orders_223
    description: Aggregates total spending's for each customer
    author: kiran+test+uimixp+2@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-09-19 13:02:56'
    datasets:
      inputs:
      - datasets/customers
      - datasets/orders
      outputs:
      - datasets/customers_orders
    subgraphs: []
    dependencies: {}
  pipelines/farmers-markets-irs:
    name: farmers-markets-irs
    description: Exploration of Farmer's Market Locations By US Zip Code
    author: kiran+test+uimixp+2@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-09-19 13:02:56'
    datasets:
      inputs:
      - 265/datasets/irs-zipcode-data
      - 265/datasets/farmers-markets
      outputs:
      - 265/datasets/farmers_market_tax_report
    subgraphs: []
    dependencies: {}
  pipelines/report_top_customers:
    name: report_top_customers
    description: Prepare a report based on customers' spending
    author: kiran+test+uimixp+2@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-09-19 13:02:56'
    datasets:
      inputs:
      - 265/datasets/customers_orders
      outputs:
      - 265/datasets/report
    subgraphs: []
    dependencies: {}
  pipelines/join_agg_sort_copy:
    name: join_agg_sort_copy
    description: Sho
    author: kiran+test+uimixp+2@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2022-10-05 13:02:56'
    datasets:
      inputs:
      - 265/datasets/orders
      - 265/datasets/customers
      outputs:
      - 265/datasets/customer_totals
    subgraphs: []
    dependencies: {}
datasets:
  datasets/orders:
    name: orders
    description: All the orders placed by the customers
    author: kiran+test+uimixp+2@prophecy.io
    createdAt: '2022-09-19 13:02:54'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 67
        datasetType: File
        description: ''
        author: kiran+test+uimixp+2@prophecy.io
        createdAt: '2022-09-19 13:02:54'
  datasets/irs-zipcode-data:
    name: irs-zipcode-data
    description: Irs zipcode data
    author: kiran+test+uimixp+2@prophecy.io
    createdAt: '2022-09-19 13:02:55'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 67
        datasetType: File
        description: ''
        author: kiran+test+uimixp+2@prophecy.io
        createdAt: '2022-09-19 13:02:55'
  datasets/customers_orders:
    name: customers_orders
    description: Customers by total of their purchases
    author: kiran+test+uimixp+2@prophecy.io
    createdAt: '2022-09-19 13:02:55'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 67
        datasetType: File
        description: ''
        author: kiran+test+uimixp+2@prophecy.io
        createdAt: '2022-09-19 13:02:55'
  datasets/customers:
    name: customers
    description: All the customers
    author: kiran+test+uimixp+2@prophecy.io
    createdAt: '2022-09-19 13:02:54'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 67
        datasetType: File
        description: ''
        author: kiran+test+uimixp+2@prophecy.io
        createdAt: '2022-09-19 13:02:54'
  datasets/farmers_market_tax_report:
    name: farmers_market_tax_report
    description: Farmer's market tax report
    author: kiran+test+uimixp+2@prophecy.io
    createdAt: '2022-09-19 13:02:56'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 67
        datasetType: File
        description: ''
        author: kiran+test+uimixp+2@prophecy.io
        createdAt: '2022-09-19 13:02:56'
  datasets/farmers-markets:
    name: farmers-markets
    description: Farmer's Market data
    author: kiran+test+uimixp+2@prophecy.io
    createdAt: '2022-09-19 13:02:55'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 67
        datasetType: File
        description: ''
        author: kiran+test+uimixp+2@prophecy.io
        createdAt: '2022-09-19 13:02:55'
  datasets/historic_events_flat:
    name: historic_events_flat
    description: Historic events flat
    author: kiran+test+uimixp+2@prophecy.io
    createdAt: '2022-09-19 13:02:55'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 67
        datasetType: File
        description: ''
        author: kiran+test+uimixp+2@prophecy.io
        createdAt: '2022-09-19 13:02:55'
  datasets/report:
    name: report
    description: Final report for the bank
    author: kiran+test+uimixp+2@prophecy.io
    createdAt: '2022-09-19 13:02:53'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 67
        datasetType: File
        description: ''
        author: kiran+test+uimixp+2@prophecy.io
        createdAt: '2022-09-19 13:02:53'
  datasets/old_events:
    name: old_events
    description: Old events data
    author: kiran+test+uimixp+2@prophecy.io
    createdAt: '2022-09-19 13:02:55'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 67
        datasetType: File
        description: ''
        author: kiran+test+uimixp+2@prophecy.io
        createdAt: '2022-09-19 13:02:55'
  datasets/customer_totals:
    name: customer_totals
    description: Customers by total of their purchases
    author: kiran+test+uimixp+2@prophecy.io
    createdAt: '2022-09-19 13:02:54'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 67
        datasetType: File
        description: ''
        author: kiran+test+uimixp+2@prophecy.io
        createdAt: '2022-09-19 13:02:54'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-06-27 06:58:26'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2024-09-17T14:02:25.008254Z'
  name: plibMaven
  version: 8.1.8
  id: '1616575543'
  createdAt: '2024-09-17T14:02:25.008183Z'
- type: plibPypi
  modifiedAt: '2024-09-17T14:02:25.008403Z'
  name: plibPypi
  version: 1.9.14
  id: '934953220'
  createdAt: '2024-09-17T14:02:25.008362Z'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.25
    isDefault: true
    author: null
    createdAt: '2024-07-31 14:55:39'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-07-31 14:55:39'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
