name: HelloWorld
description: ''
version: '1'
author: ''
language: python
buildSystem: wheel
pipelines:
  pipelines/report_top_customers:
    name: report_top_customers
    description: Prepare a report based on customers' spending
    author: kiranadmin@prophecy.io
    mode: batch
    language: python
    createdAt: '2022-09-11 08:53:05'
    datasets:
      inputs:
      - datasets/customers_orders
      outputs:
      - datasets/report
    dependencies: {}
  pipelines/join_agg_sort:
    name: join_agg_sort
    description: Show an example of joining two datasets (customers and orders), aggregating
      (sales by customer), sorting (by totals)
    author: kiranadmin@prophecy.io
    mode: batch
    language: python
    createdAt: '2022-09-11 08:53:05'
    datasets:
      inputs:
      - 606/datasets/orders
      - 606/datasets/customers
      outputs:
      - 606/datasets/customer_totals
    dependencies: {}
  pipelines/farmers-markets-irs:
    name: farmers-markets-irs
    description: Exploration of Farmer's Market Locations By US Zip Code
    author: kiranadmin@prophecy.io
    mode: batch
    language: python
    createdAt: '2022-09-11 08:53:05'
    datasets:
      inputs:
      - 606/datasets/irs-zipcode-data
      - 606/datasets/farmers-markets
      outputs:
      - 606/datasets/farmers_market_tax_report
    dependencies: {}
  pipelines/customers_orders:
    name: customers_orders
    description: Aggregates total spending's for each customer
    author: kiranadmin@prophecy.io
    mode: batch
    language: python
    createdAt: '2022-09-11 08:53:05'
    datasets:
      inputs:
      - 606/datasets/orders
      - 606/datasets/customers
      outputs:
      - 606/datasets/customers_orders
    dependencies: {}
datasets:
  datasets/orders:
    name: orders
    description: All the orders placed by the customers
    author: kiranadmin@prophecy.io
    createdAt: '2022-09-11 08:53:03'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 166
        datasetType: File
        description: ''
        author: kiranadmin@prophecy.io
        createdAt: '2022-09-11 08:53:03'
  datasets/irs-zipcode-data:
    name: irs-zipcode-data
    description: Irs zipcode data
    author: kiranadmin@prophecy.io
    createdAt: '2022-09-11 08:53:04'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 166
        datasetType: File
        description: ''
        author: kiranadmin@prophecy.io
        createdAt: '2022-09-11 08:53:04'
  datasets/customers_orders:
    name: customers_orders
    description: Customers by total of their purchases
    author: kiranadmin@prophecy.io
    createdAt: '2022-09-11 08:53:04'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 166
        datasetType: File
        description: ''
        author: kiranadmin@prophecy.io
        createdAt: '2022-09-11 08:53:04'
  datasets/customers:
    name: customers
    description: All the customers
    author: kiranadmin@prophecy.io
    createdAt: '2022-09-11 08:53:03'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 166
        datasetType: File
        description: ''
        author: kiranadmin@prophecy.io
        createdAt: '2022-09-11 08:53:03'
  datasets/farmers_market_tax_report:
    name: farmers_market_tax_report
    description: Farmer's market tax report
    author: kiranadmin@prophecy.io
    createdAt: '2022-09-11 08:53:05'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 166
        datasetType: File
        description: ''
        author: kiranadmin@prophecy.io
        createdAt: '2022-09-11 08:53:05'
  datasets/farmers-markets:
    name: farmers-markets
    description: Farmer's Market data
    author: kiranadmin@prophecy.io
    createdAt: '2022-09-11 08:53:04'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 166
        datasetType: File
        description: ''
        author: kiranadmin@prophecy.io
        createdAt: '2022-09-11 08:53:04'
  datasets/historic_events_flat:
    name: historic_events_flat
    description: Historic events flat
    author: kiranadmin@prophecy.io
    createdAt: '2022-09-11 08:53:04'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 166
        datasetType: File
        description: ''
        author: kiranadmin@prophecy.io
        createdAt: '2022-09-11 08:53:04'
  datasets/report:
    name: report
    description: Final report for the bank
    author: kiranadmin@prophecy.io
    createdAt: '2022-09-11 08:53:02'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 166
        datasetType: File
        description: ''
        author: kiranadmin@prophecy.io
        createdAt: '2022-09-11 08:53:02'
  datasets/old_events:
    name: old_events
    description: Old events data
    author: kiranadmin@prophecy.io
    createdAt: '2022-09-11 08:53:04'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 166
        datasetType: File
        description: ''
        author: kiranadmin@prophecy.io
        createdAt: '2022-09-11 08:53:04'
  datasets/customer_totals:
    name: customer_totals
    description: Customers by total of their purchases
    author: kiranadmin@prophecy.io
    createdAt: '2022-09-11 08:53:03'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 166
        datasetType: File
        description: ''
        author: kiranadmin@prophecy.io
        createdAt: '2022-09-11 08:53:03'
templates: {}
jobs: {}
libraries: []
subgraphs: {}
sqlModels: {}
sqlPipeline: null
dependencies: '[]'
projectDependencies: {}
pipelineConfigurations: {}
